# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubRepoTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubRepoTask
   pod 'IQKeyboardManagerSwift'
   pod 'R.swift'
   pod 'SwiftyJSON', '~> 4.0'
   pod 'MBProgressHUD', '~> 1.1.0'
   pod 'CleanyModal'
   pod 'NVActivityIndicatorView/AppExtension'
   pod 'lottie-ios'

end
